### ISSUE TITLE
Update to Font-Awesome 4.6.1

### ISSUE THREAD

**Issue by mavinger** [MeteorPackaging/Font-Awesome#11]
Need to update to Font-Awesome 4.6.1

@splendido I know you are a busy guy. Would a version bump do the trick or did the release of Meteor 1.3.x change things? Has the integration with npm made this type of packaging obsolete? Thanks for your time!

**Comment by acomito** [comment]
Yes! My app is getting mangled in safari without the update. I still use 1.2 so I could care less if it works with 1.3

https://github.com/FortAwesome/Font-Awesome/issues/5043

**Comment by dandv** [comment]
> I still use 1.2 so I could care less if it works with 1.3

Let's be respectful here. @splendido has put in a lot of effort into this project, and if you can't be bothered to upgrade your app to 1.3, you might imagine that others might also not care to support a deprecated way of packaging 3rd party libraries for Meteor just for one use case.
