### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by olumytee** [MeteorPackaging/Font-Awesome#14]
Hello, can you update to the latest version ? Thanks

**Comment by RichDonnellan** [comment]
Pull request (#13) aimed to do this, but there hasn't been much activity.

@dandv @splendido: Any plans to merge this?

**Comment by dandv** [comment]
We recommend using npm now that Meteor 1.3+ supports npm packages natively.

**Comment by RichDonnellan** [comment]
@dandv: Sadly, certain companies can not/will not upgrade to v1.3. There are quite a few people that commented on the PR that probably fall into this boat. Any way you can merge it?

**Comment by dandv** [comment]
I've just published the package to Atmosphere. Couldn't run the tests and given the obsolete status of this package, I doubt it's worth @splendido's time to look into it.
